library(groundhog)
groundhog.library(c('tidyverse'),
                  "2022-12-01")

fruit_from_wiki <- "*[[Abiu]]
*[[Acai]]
*[[Acerola]]
*[[Akebi]]
*[[Ackee]]
*[[African Cherry Orange]]
*[[American Mayapple]]
*[[Apple]]
*[[Apricot]]
*[[Araza]]
*[[Avocado]]
*[[Banana]]
*[[Bilberry]]
*[[Blackberry]]
*[[Blackcurrant]]
*[[Black sapote]]
*[[Blueberry]]
*[[Boysenberry]]
*[[Breadfruit]]
*[[Buddhas hand]]
*[[Cactus pear]]
*[[Canistel]]
*[[Cashew]]
*[[Cempedak]]
*[[Cherimoya]]
*[[Cherry]]
*[[Chico fruit]]
*[[Cloudberry]]
*[[Coco De Mer]]
*[[Coconut]]
*[[Crab apple]]
*[[Cranberry]]
*[[Currant]]
*[[Damson]]
*[[Date palm|Date]]
*[[Dragonfruit]]
*[[Pitaya]]
*[[Durian]]
*[[Egg Fruit]]
*[[Elderberry]]
*[[Feijoa]]
*[[Fig]]
*[[Finger Lime]]
*[[Caviar Lime]]
*[[Goji berry]]
*[[Gooseberry]]
*[[Grape]]
*[[Raisin]]
*[[Grapefruit]]
*[[Grewia asiatica (phalsa or falsa)]]
*[[Guava]]
*[[Hala Fruit]]
*[[Honeyberry]]
*[[Huckleberry]]
*[[Jabuticaba]]
*[[Jackfruit]]
*[[Jambul]]
*[[Japanese plum]]
*[[Jostaberry]]
*[[Jujube]]
*[[Juniper berry]]
*[[Kaffir Lime]]
*[[Kiwano]]
*[[Kiwifruit]]
*[[Kumquat]]
*[[Lemon]]
*[[Lime]]
*[[Loganberry]]
*[[Longan]]
*[[Loquat]]
*[[Lulo]]
*[[Lychee]]
*[[Magellan Barberry]]
*[[Mamey Apple]]
*[[Mamey Sapote]]
*[[Mango]]
*[[Mangosteen]]
*[[Marionberry]]
*[[Melon]]
**[[Cantaloupe]]
**[[Galia melon]]
**[[Honeydew]]
**[[Mouse melon]]
**[[Musk melon]]
**[[Watermelon]]
*[[Miracle fruit]]
*[[Momordica fruit]]
*[[Monstera deliciosa]]
*[[Mulberry]]
*[[Nance]]
*[[Nectarine]]
*[[Orange]]
**[[Blood orange]]
**[[Clementine]]
**[[Mandarine]]
**[[Tangerine]]
*[[Papaya]]
*[[Passionfruit]]
*[[Pawpaw]]
*[[Peach]]
*[[Pear]]
*[[Persimmon]]
*[[Plantain]]
*[[Plum]]
**[[Prune]]
*[[Pineapple]]
*[[Pineberry]]
*[[Plumcot]]
*[[Pomegranate]]
*[[Pomelo]]
*[[Purple mangosteen]]
*[[Quince]]
*[[Raspberry]]
**[[Salmonberry]]
*[[Rambutan]]
*[[Redcurrant]]
*[[Rose apple]]
*[[Salal]] berry
*[[Salak]]
*[[Sapodilla]]
*[[Sapote]]
*[[Satsuma]]
*[[Shine Muscat]]
*[[Sloey]]
*[[Soursop]]
*[[Star apple]]
*[[Star fruit]]
*[[Strawberry]]
*[[Surinam cherry]]
*[[Tamarillo]]
*[[Tamarind]]
*[[Tangelo]]
*[[Tayberry]]
*[[Ugli fruit]]
*[[White currant]]
*[[White sapote]]
*[[Ximenia]]
*[[Yuzu]]}}
*[[Bell pepper]]
*[[Chile pepper]]
*[[Corn kernel]]
*[[Cucumber]]
*[[Eggplant]]
*[[Jalapeño]]
*[[Olive]]
*[[Pea]]
*[[Pumpkin]]
*[[Squash]]
*[[Tomato]]
*[[Zucchini]]}}
"

fruit_list <- fruit_from_wiki %>%
  str_replace_all("[[:punct:]]", "") %>%
  strsplit('\n')

fruit_list = fruit_list[[1]]

basic_fruit <- data.frame(word = tolower(fruit_list)) %>%
  mutate(score= 7)

proto_fruit <- read.csv('word_lists/fruit_proto.csv')


word_df <- proto_fruit %>%
  bind_rows(basic_fruit) %>%
  mutate(word=trimws(word))%>%
  group_by(word)%>%
  summarize(score=min(score))%>%
  ungroup()%>%
  mutate(invscore=1/score,
         prior=invscore/sum(invscore))


word_df %>%
  write.csv('word_lists/fruit.csv')

